name: paasta-glusterfs-service                       # 서비스 배포이름(필수)
director_uuid: 93b19179-c3d8-456b-9c52-5f0fe1adea0e  # bosh status 에서 확인한 Director UUID을 입력(필수)

releases:
- name: paasta-glusterfs                             # 서비스 릴리즈 이름(필수)
  version: 2.0                                       # 서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

update:
  canaries: 1                                        # canary 인스턴스 수(필수)
  canary_watch_time: 30000-600000                    # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 30000-600000                    # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 1                                   # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)

compilation:                         # 컴파일시 필요한 가상머신의 속성(필수)
  workers: 1                         # 컴파일 하는 가상머신의 최대수(필수)
  network: default                   # Networks block에서 선언한 network 이름(필수)
  reuse_compilation_vms: true
  cloud_properties:                  # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성 (instance_type, availability_zone)
    availability_zone: ap-northeast-2a
    instance_type: c4.large

jobs:
- instances: 1                    # job 인스턴스 수(필수)
  name: mysql                     # 작업 이름(필수): MySQL 서버
  networks:                       # 네트워크 구성정보
  - name: default          # Networks block에서 선언한 network 이름(필수)
    static_ips: 10.0.0.196     # 사용할 IP addresses 정의(필수): MySQL 서버 IP
#  persistent_disk: 1024          # 영구적 디스크 사이즈 정의(옵션): 1G, 상황에 맞게 수정
  properties:                     # job에 대한 속성을 지정(필수)
    admin_username: root          # MySQL 어드민 계정
    admin_password: admin         # MySQL 어드민 패스워드
  release: paasta-glusterfs       # 서비스 릴리즈 이름(필수)
  resource_pool: resource_pools   # Resource Pools block에 정의한 resource pool 이름(필수)
  template: mysql                 # job template 이름(필수)

- instances: 1                    # job 인스턴스 수(필수)
  name: paasta-glusterfs-broker   # job 인스턴스 수(필수)
  networks:                       # job 인스턴스 수(필수)
  - name: default          # Networks block에서 선언한 network 이름(필수)
    static_ips: 10.0.0.197          # service broker IP(필수)
  properties:               job에 대한 속성을 지정(필수)
    jdbc_ip: 10.0.0.196             # Mysql IP(필수)
    jdbc_pwd: admin                    # Mysql password(필수)
    jdbc_port: 3306                    # Mysql Port
    log_dir: paasta-glusterf-broker   # Broker Log 저장 디렉토리 명
    log_file: paasta-glusterfs-broker  # Broker Log 저장 파일 명
    log_level: INFO                    # Broker Log 단계
    glusterfs_url: 52.201.48.51        # Glusterfs 서비스 주소
    glusterfs_tenantname: service      # Glusterfs 서비스 테넌트 이름
    glusterfs_username: swift          # Glusterfs 서비스 계정 아이디
    glusterfs_password: password       # Glusterfs 서비스 암호
  release: paasta-glusterfs
  resource_pool: resource_pools
  template: op-glusterfs-java-broker

- instances: 1
  lifecycle: errand                    # bosh deploy시 vm에 생성되어 설치 되지 않고 bosh errand 로실행할때 설정, 주로 테스트 용도에 쓰임
  name: broker-registrar
  networks:
  - name: default
  properties:
    broker:
      host: 10.0.0.197          # Service Broker IP
      name: glusterfs-service      # Service Broker Name
      password: cloudfoundry       # Service Broker Auth Password
      username: admin              # Service Broker Auth Id
      protocol: http               # Service Broker Http Protocol
      port: 8080                   # Service Broker port
    cf:
      admin_password: admin                      # CF Paasword
      admin_username: admin                      # CF Id
      api_url: https://api.52.71.217.204.xip.io  # CF Target Url
      skip_ssl_validation: true                  # CF SSL 설정
  release: paasta-glusterfs
  resource_pool: resource_pools
  template: broker-registrar

- instances: 1
  lifecycle: errand
  name: broker-deregistrar
  networks:
  - name: default
  properties:
    broker:                      
      name: glusterfs-service                      
    cf:                      
      admin_username: admin                      # CF Paasword
      admin_password: admin                      # CF Id
      api_url: https://api.52.71.217.204.xip.io  # CF Target Url 
      skip_ssl_validation: true                  # CF SSL 설정
  release: paasta-glusterfs
  resource_pool: resource_pools
  template: broker-deregistrar

networks:                                   # 네트워크 블록에 나열된 각 서브 블록이 참조 할 수있는 작업이 네트워크 구성을 지정, 네트워크 구성은 네트워크 담당자에게 문의 하여 작성 요망
- name: default
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns: [10.0.0.6, 8.8.8.8]                      # DNS 정보
    reserved: ["10.0.0.2 - 10.0.0.189"]           # 설치시 제외할 IP 설정
    static: ["10.0.0.190 - 10.0.0.200"]           # 사용 가능한 IP 설정
    cloud_properties:
      subnet: subnet-cdfc80a4                     # AWS subnet id
      security_groups:
        - psta-cf-security
        - psta-bosh-security

properties: {}

resource_pools:               # 배포시 사용하는 resource pools를 명시하며 여러 개의 resource pools 을 사용할 경우 name 은 unique 해야함(필수)
  - name: resource_pools      # 고유한 resource pool 이름
    network: default
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent  # stemcell 이름(필수)
      version: 3309            # stemcell 버전(필수)
    cloud_properties:          # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성을 설명 (instance_type, availability_zone), 직접 cpu, disk, 메모리 설정가능
      instance_type: t2.small
      availability_zone: ap-northeast-2a