name: paasta-glusterfs-service                       # 서비스 배포이름(필수)
director_uuid: d363905f-eaa0-4539-a461-8c1318498a32  # bosh status 에서 확인한 Director UUID을 입력(필수)

releases:
- name: paasta-glusterfs             # 서비스 릴리즈 이름(필수)
  version: 2.0                       # 서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

update:
  canaries: 1                        # canary 인스턴스 수(필수)
  canary_watch_time: 30000-600000    # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 1                   # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  update_watch_time: 30000-600000    # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)

compilation:                      # 컴파일시 필요한 가상머신의 속성(필수)
  cloud_properties:               # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성 (instance_type, availability_zone), 직접 cpu,disk,ram 사이즈를 넣어도 됨
    cpu: 4
    disk: 20480
    ram: 4096
  network: paasta_network         # Networks block에서 선언한 network 이름(필수)
  reuse_compilation_vms: true     # 컴파일지 VM 재사용 여부(옵션)
  workers: 2                      # 컴파일 하는 가상머신의 최대수(필수)

jobs:
- instances: 1                    # job 인스턴스 수(필수)
  name: mysql                     # 작업 이름(필수): MySQL 서버
  networks:                       # 네트워크 구성정보
  - name: paasta_network          # Networks block에서 선언한 network 이름(필수)
    static_ips: 10.30.120.196     # 사용할 IP addresses 정의(필수): MySQL 서버 IP
#  persistent_disk: 1024          # 영구적 디스크 사이즈 정의(옵션): 1G, 상황에 맞게 수정
  properties:                     # job에 대한 속성을 지정(필수)
    admin_username: root          # MySQL 어드민 계정
    admin_password: admin         # MySQL 어드민 패스워드
  release: paasta-glusterfs       # 서비스 릴리즈 이름(필수)
  resource_pool: services-small   # Resource Pools block에 정의한 resource pool 이름(필수)
  template: mysql                 # job template 이름(필수)

- instances: 1
  name: paasta-glusterfs-broker
  networks:
  - name: paasta_network
    static_ips: 10.30.120.197          # service broker IP(필수)
  properties:
    jdbc_ip: 10.30.120.196             # Mysql IP(필수)
    jdbc_pwd: admin                    # Mysql password(필수)
    jdbc_port: 3306                    # Mysql Port
    log_dir: paasta-glusterfs-broker   # Broker Log 저장 디렉토리 명
    log_file: paasta-glusterfs-broker  # Broker Log 저장 파일 명
    log_level: INFO                    # Broker Log 단계
    glusterfs_url: 52.201.48.51        # Glusterfs 서비스 주소
    glusterfs_tenantname: service      # Glusterfs 서비스 테넌트 이름
    glusterfs_username: swift          # Glusterfs 서비스 계정 아이디
    glusterfs_password: password       # Glusterfs 서비스 암호
  release: paasta-glusterfs
  resource_pool: services-small
  template: op-glusterfs-java-broker

- instances: 1
  lifecycle: errand                    # bosh deploy시 vm에 생성되어 설치 되지 않고 bosh errand 로실행할때 설정, 주로 테스트 용도에 쓰임
  name: broker-registrar
  networks:
  - name: paasta_network
  properties:
    broker:
      host: 10.30.120.197          # Service Broker IP
      name: glusterfs-service      # Service Broker Name
      password: cloudfoundry       # Service Broker Auth Password
      username: admin              # Service Broker Auth Id
      protocol: http               # Service Broker Http Protocol
      port: 8080                   # Service Broker port
    cf:
      admin_password: admin                      # CF Paasword
      admin_username: admin                      # CF Id
      api_url: https://api.115.68.46.186.xip.io   # CF Target Url
      skip_ssl_validation: true                  # CF SSL 설정
  release: paasta-glusterfs
  resource_pool: services-small
  template: broker-registrar

- instances: 1
  lifecycle: errand
  name: broker-deregistrar
  networks:
  - name: paasta_network
  properties:
    broker:
      name: glusterfs-service
    cf:
      admin_password: admin
      admin_username: admin
      api_url: https://api.115.68.46.186.xip.io
      skip_ssl_validation: true
  release: paasta-glusterfs
  resource_pool: services-small
  template: broker-deregistrar

networks:                        # 네트워크 블록에 나열된 각 서브 블록이 참조 할 수있는 작업이 네트워크 구성을 지정, 네트워크 구성은 네트워크 담당자에게 문의 하여 작성 요망
- name: paasta_network
  subnets:
  - cloud_properties:
      name: Internal             # vsphere 에서 사용하는 network 이름(필수)
    dns:                         # DNS 정보
    - 10.30.20.24
    - 8.8.8.8
    gateway: 10.30.20.23
    name: default_unused
    range: 10.30.0.0/16
    reserved:                           # 설치시 제외할 IP 설정
    - 10.30.0.1 - 10.30.0.5
    static:                             # 사용 가능한 IP 설정
    - 10.30.120.190 - 10.30.120.200
  type: manual                          # 네트워크 설정 타입
properties: {}
resource_pools:               # 배포시 사용하는 resource pools를 명시하며 여러 개의 resource pools 을 사용할 경우 name 은 unique 해야함(필수)        
- cloud_properties:           # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성을 설명 (instance_type, availability_zone), 직접 cpu, disk, 메모리 설정가능
    cpu: 1
    disk: 8192
    ram: 1024
  name: services-small        # 고유한 resource pool 이름
  #size: 5                    # resource pool 안의 가상머신 개수, 주의) jobs 인스턴스 보다 작으면 에러가 남, size 정의하지 않으면 자동으로 가상머신 크기 설정
  network: paasta_network       
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent    # stemcell 이름(필수)
    version: "3309"                                 # stemcell 버전(필수)
